language: php

php:
  - 5.4
  - 5.5

before_script:
  - phantomjs --webdriver=4444 &
  - php -S localhost:1234 -t tests/data/ &
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: false
